---
sidebar: sidebar 
permalink: create-workspaces.html 
keywords: manage, workspace, snapshot, project 
summary: 'Un"area di lavoro in NetApp Workload Factory for Builders è una rappresentazione Perforce di un progetto basata su uno snapshot del progetto.  È possibile creare spazi di lavoro come parte di un progetto Builder.' 
---
= Creare un'area di lavoro Builders
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Un'area di lavoro in NetApp Workload Factory for Builders è una rappresentazione Perforce di un progetto in un momento specifico.  Gli spazi di lavoro vengono creati utilizzando come base uno snapshot del progetto.  È possibile creare nuovi spazi di lavoro all'interno di un progetto Builder.  È possibile creare spazi di lavoro dall'interfaccia utente di Perforce.

.Prima di iniziare
Assicurarsi di avere integrato i costruttori con il client Visual Perforce Helix. Per ulteriori informazioni, vedere link:integrate-perforce.html["Integrare costruttori con Perforce"^] .

.Fasi
. Accedere a Perforce.
. Nel menu Perforce, selezionare *View* > *WF*.
+
La schermata di accesso a Workload Factory viene visualizzata nell'interfaccia utente di Perforce.

. Accedi a Workload Factory utilizzando uno deilink:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^] .
. Nel riquadro Carichi di lavoro Builder, seleziona *Crea progetto*.
. Selezionare *Crea area di lavoro*.
. Nella pagina Crea un progetto area di lavoro, fornire quanto segue:
+
.. Selezionare un'istantanea da utilizzare come base per l'area di lavoro.
.. Immettere un nome per l'area di lavoro.
.. Facoltativamente, immettere un identificativo utente per richiedere l'area di lavoro. Questo identificatore deve corrispondere all'ID utente Perforce dello sviluppatore che utilizzerà questa area di lavoro.


. Selezionare *Crea*.


.Risultato
L'area di lavoro viene creata e viene visualizzata nell'elenco delle aree di lavoro nella pagina aree di lavoro.
