---
sidebar: sidebar 
permalink: requirements-builders.html 
keywords: Builders, FSx, project, projects 
summary: Verificare che la workload Factory e AWS siano configurati correttamente prima di iniziare a utilizzare la fabbrica di carichi di lavoro BlueXP  per i costruttori. Ciò include la possibilità di avere le credenziali di log in di AWS, un file system FSX per ONTAP implementato e altro ancora. 
---
= Requisiti dei costruttori
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Verificare che la workload Factory e AWS siano configurati correttamente prima di iniziare a utilizzare la fabbrica di carichi di lavoro BlueXP  per i costruttori. Ciò include la possibilità di avere le credenziali di log in di AWS, un file system FSX per ONTAP implementato e altro ancora.

Account e login di fabbrica del carico di lavoro:: Sarà necessario https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["configurare un account con workload factory"^] ed effettuare l'accesso utilizzando uno dei https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^] .
Credenziali e autorizzazioni AWS:: Devi aggiungere le credenziali AWS alla fabbrica dei carichi di lavoro con autorizzazioni di lettura/scrittura, il che significa che utilizzerai la fabbrica dei carichi di lavoro in modalità _lettura/scrittura_ per i costruttori.


Le autorizzazioni per la modalità _Basic_ e la modalità _Read-only_ non sono attualmente supportate. https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come aggiungere le credenziali AWS alla fabbrica di carichi di lavoro"^]

File system FSX per ONTAP:: Ti serve almeno un file system FSX per ONTAP:
+
--
* Il file system verrà utilizzato dai costruttori per memorizzare i progetti e le aree di lavoro creati.
+
Questo file system FSX per ONTAP deve usare FlexVol Volumes. I volumi FlexGroup non sono supportati.

* Dovrai conoscere la regione, il VPC e la subnet di AWS in cui si trova il file system AWS FSX per ONTAP.
* È necessario almeno un volume nel filesystem con la seguente configurazione:
+
** Il volume deve essere configurato come condivisione NFS.
** Il filesystem deve essere configurato con un link. https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Ulteriori informazioni sui collegamenti"^].


* Dovrai prendere in considerazione le coppie tag key/valore che desideri applicare alle risorse AWS che fanno parte di questa implementazione (opzionale).
+
https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Scopri come implementare e gestire i file system FSX per ONTAP"^]



--

