---
sidebar: sidebar 
permalink: requirements-builders.html 
keywords: Builders, FSx, project, projects 
summary: Prima di iniziare a utilizzare NetApp Workload Factory for Builders, assicurati che Workload Factory e AWS siano configurati correttamente.  Ciò include avere le credenziali di accesso AWS, un file system FSx per ONTAP distribuito e altro ancora. 
---
= Requisiti dei costruttori
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Prima di iniziare a utilizzare NetApp Workload Factory for Builders, assicurati che Workload Factory e AWS siano configurati correttamente.  Ciò include avere le credenziali di accesso AWS, un file system FSx per ONTAP distribuito e altro ancora.

Account e login di fabbrica del carico di lavoro:: Avrai bisogno di https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["creare un account con Workload Factory"^] e accedi utilizzando uno dei https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^] .
Credenziali e autorizzazioni AWS:: È necessario aggiungere le credenziali AWS a Workload Factory con autorizzazioni di lettura/scrittura, il che significa che utilizzerai Workload Factory in modalità _lettura/scrittura_ per i Builder.


Al momento, le autorizzazioni in modalità _base_ e _sola lettura_ non sono supportate.https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come aggiungere le credenziali AWS a Workload Factory"^]

File system FSX per ONTAP:: Ti serve almeno un file system FSX per ONTAP:
+
--
* Il file system verrà utilizzato dai costruttori per memorizzare i progetti e le aree di lavoro creati.
+
Questo file system FSX per ONTAP deve usare FlexVol Volumes. I volumi FlexGroup non sono supportati.

* Dovrai conoscere la regione, il VPC e la subnet di AWS in cui si trova il file system AWS FSX per ONTAP.
* È necessario almeno un volume nel filesystem con la seguente configurazione:
+
** Il volume deve essere configurato come condivisione NFS.
** Il filesystem deve essere configurato con un link. https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Ulteriori informazioni sui collegamenti"^].


* Dovrai prendere in considerazione le coppie tag key/valore che desideri applicare alle risorse AWS che fanno parte di questa implementazione (opzionale).
+
https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Scopri come implementare e gestire i file system FSX per ONTAP"^]



--

