---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, builders, workload factory' 
summary: Scopri le novità della workload factory per i database. 
---
= Novità di BlueXP  workload Factory per i costruttori
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità della funzionalità costruttori di workload Factory.



== 1 dicembre 2024



=== Rilascio iniziale del carico di lavoro dei costruttori

BlueXP  workload Factory for Builders semplifica l'utilizzo e l'accesso delle versioni software, eliminando la necessità di strumenti o script personalizzati. Consente di utilizzare le versioni software come cloni istantanei integrati con Perforce Helix Core come spazio di lavoro comodo per i processi di sviluppo, risparmiando tempo e risorse.

La release iniziale include la capacità di gestire progetti e aree di lavoro e automatizzare azioni con Codebox. È inoltre possibile integrare i costruttori con Perforce Helix Core, in modo da poter gestire diverse versioni di ciascun progetto e passare rapidamente da un progetto all'altro.
