---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, Workload Factory, builders, Workload Factory' 
summary: Scopri le novità di Workload Factory per database. 
---
= Novità di NetApp Workload Factory for Builders
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità della funzionalità Builders di Workload Factory.



== 5 ottobre 2025



=== La BlueXP workload factory ora è NetApp Workload Factory

BlueXP è stato rinominato e riprogettato per riflettere meglio il ruolo che svolge nella gestione dell'infrastruttura dati.  Di conseguenza, BlueXP workload factory è stato rinominato NetApp Workload Factory.



== 16 giugno 2025



=== Supporto per clonazione

Ora puoi clonare un progetto in BlueXP Workload Factory for Builders.  Quando si clona un progetto, Builders crea un nuovo progetto da uno snapshot, con la stessa configurazione dell'originale.  La clonazione è utile per creare rapidamente progetti simili o per scopi di test.  È possibile montare il nuovo clone del progetto seguendo le istruzioni in Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Gestisci le versioni dei progetti BlueXP Workload Factory for Builders"]



== 4 maggio 2025



=== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione di Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



== 1 dicembre 2024



=== Rilascio iniziale del carico di lavoro dei costruttori

BlueXP Workload Factory for Builders semplifica l'utilizzo e l'accesso alle versioni del software, eliminando la necessità di strumenti o script personalizzati.  Ti consente di utilizzare versioni software come cloni istantanei integrati con Perforce Helix Core come comodo spazio di lavoro per i tuoi processi di sviluppo, risparmiando tempo e risorse.

La release iniziale include la capacità di gestire progetti e aree di lavoro e automatizzare azioni con Codebox. È inoltre possibile integrare i costruttori con Perforce Helix Core, in modo da poter gestire diverse versioni di ciascun progetto e passare rapidamente da un progetto all'altro.
